name: buhoor
description: "Arabic poetry app."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.7.0
  connectivity_plus: ^6.1.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.2
  pinput: ^5.0.1
  email_validator: ^3.0.0
  json_annotation: ^4.9.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.5
  email_otp: ^3.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - assets/